spring.application.name=gestao-loja-api

# 1. Configuração da Base de Dados (MySQL)
# Altera "nome_da_tua_base_de_dados" pelo nome do esquema que criaste no MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_gestao_loja?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=71ovl3FH!@#

# 2. Configurações do Hibernate / JPA (A inteligência do Servidor)
# Mostra no painel de controlo do IntelliJ o comando SQL exato que o Spring está a executar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Esta linha faz o Spring criar ou atualizar as tabelas do MySQL automaticamente com base nas tuas classes Java!
spring.jpa.hibernate.ddl-auto=update